# Inferring Topics from IMDB Reviews

In [1]:
import numpy as np
import os
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF
import pandas as pd
import matplotlib.pyplot as plt

## Exploring the Dataset: [Large Movie Review Dataset](https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz)

In [10]:
ROOT = r'C:\Users\arnig\Documents\Coding_2024\python_work\UpGrad\DS_C70\Specialization_NLP\Semantic-Processing\semantic_processing_upgrad\Topic Modelling\data\aclImdb_v1\aclImdb\train\pos'

In [ ]:
reviews = []
for file in os.listdir(ROOT):               # Lists all files in the directory
    path = os.path.join(ROOT, file)         # Gets the file paths of file in directory
    if os.path.isfile(path):
        with open(path, 'r', encoding='utf-8') as fin:
            reviews.append(fin.read())

In [24]:
# print(os.listdir(ROOT)[100])
# print(os.path.join(ROOT, os.listdir(ROOT)[100]))

In [12]:
len(reviews)

12500

In [25]:
for i in range(3):
    print(reviews[i])
    print('=' * 150)

Bromwell High is a cartoon comedy. It ran at the same time as some other programs about school life, such as "Teachers". My 35 years in the teaching profession lead me to believe that Bromwell High's satire is much closer to reality than is "Teachers". The scramble to survive financially, the insightful students who can see right through their pathetic teachers' pomp, the pettiness of the whole situation, all remind me of the schools I knew and their students. When I saw the episode in which a student repeatedly tried to burn down the school, I immediately recalled ......... at .......... High. A classic line: INSPECTOR: I'm here to sack one of your teachers. STUDENT: Welcome to Bromwell High. I expect that many adults of my age think that Bromwell High is far fetched. What a pity that it isn't!
======================================================================================================================================================
Homelessness (or Houselessness as George Carlin stated) has been an issue for years but never a plan to help those on the street that were once considered human who did everything from going to school, work, or vote for the matter. Most people think of the homeless as just a lost cause while worrying about things such as racism, the war on Iraq, pressuring kids to succeed, technology, the elections, inflation, or worrying if they'll be next to end up on the streets.<br /><br />But what if you were given a bet to live on the streets for a month without the luxuries you once had from a home, the entertainment sets, a bathroom, pictures on the wall, a computer, and everything you once treasure to see what it's like to be homeless? That is Goddard Bolt's lesson.<br /><br />Mel Brooks (who directs) who stars as Bolt plays a rich man who has everything in the world until deciding to make a bet with a sissy rival (Jeffery Tambor) to see if he can live in the streets for thirty days without the luxuries; if Bolt succeeds, he can do what he wants with a future project of making more buildings. The bet's on where Bolt is thrown on the street with a bracelet on his leg to monitor his every move where he can't step off the sidewalk. He's given the nickname Pepto by a vagrant after it's written on his forehead where Bolt meets other characters including a woman by the name of Molly (Lesley Ann Warren) an ex-dancer who got divorce before losing her home, and her pals Sailor (Howard Morris) and Fumes (Teddy Wilson) who are already used to the streets. They're survivors. Bolt isn't. He's not used to reaching mutual agreements like he once did when being rich where it's fight or flight, kill or be killed.<br /><br />While the love connection between Molly and Bolt wasn't necessary to plot, I found "Life Stinks" to be one of Mel Brooks' observant films where prior to being a comedy, it shows a tender side compared to his slapstick work such as Blazing Saddles, Young Frankenstein, or Spaceballs for the matter, to show what it's like having something valuable before losing it the next day or on the other hand making a stupid bet like all rich people do when they don't know what to do with their money. Maybe they should give it to the homeless instead of using it like Monopoly money.<br /><br />Or maybe this film will inspire you to help others.
======================================================================================================================================================
Brilliant over-acting by Lesley Ann Warren. Best dramatic hobo lady I have ever seen, and love scenes in clothes warehouse are second to none. The corn on face is a classic, as good as anything in Blazing Saddles. The take on lawyers is also superb. After being accused of being a turncoat, selling out his boss, and being dishonest the lawyer of Pepto Bolt shrugs indifferently "I'm a lawyer" he says. Three funny words. Jeffrey Tambor, a favorite from the later Larry Sanders show, is fantastic here too as a mad millionaire who wants to crush the ghetto. His character is more malevolent than usual. The hospital scene, and the scene where the homeless invade a demolition site, are all-time classics. Look for the legs scene and the two big diggers fighting (one bleeds). This movie gets better each time I see it (which is quite often).
======================================================================================================================================================

## Feature Extraction

In [26]:
vect = TfidfVectorizer(stop_words='english')
X = vect.fit_transform(reviews)

pd.DataFrame(X.toarray(), columns=vect.get_feature_names_out())

,00,000,000s,003830,006,007,0079,0080,0083,0093638,...,élan,émigré,émigrés,était,état,étc,êxtase,ís,østbye,über
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12495,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12496,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12497,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12498,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12499,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## NMF Decomposition

In [30]:
N_TOPICS = 20
nmf = NMF(n_components=N_TOPICS, max_iter=1000)
W = nmf.fit_transform(X)  # Document-topic matrix
H = nmf.components_       # Topic-term matrix

In [32]:
# Top 10 words per topic

words = np.array(vect.get_feature_names_out())
topic_words = pd.DataFrame(np.zeros((N_TOPICS, 10)), index=[f'Topic {i + 1}' for i in range(N_TOPICS)],
                           columns=[f'Word {i + 1}' for i in range(10)]).astype(str)
for i in range(N_TOPICS):
    ix = H[i].argsort()[::-1][:10]
    topic_words.iloc[i] = words[ix]

topic_words

,Word 1,Word 2,Word 3,Word 4,Word 5,Word 6,Word 7,Word 8,Word 9,Word 10
Topic 1,br,10,ll,spoilers,end,simply,yes,spoiler,just,stars
Topic 2,movie,movies,watch,10,recommend,definitely,enjoyed,feel,makes,better
Topic 3,film,films,director,festival,cinema,characters,scenes,work,plot,art
Topic 4,episode,season,episodes,columbo,shows,seasons,characters,television,tony,sabrina
Topic 5,man,role,character,performance,father,john,plays,young,played,wife
Topic 6,good,pretty,story,bad,acting,job,really,actors,nice,liked
Topic 7,series,tv,episodes,war,original,gundam,sci,fi,new,trek
Topic 8,funny,comedy,laugh,hilarious,eddie,jokes,fun,humor,funniest,murphy
Topic 9,time,years,saw,dvd,old,remember,tv,ago,watched,watch
Topic 10,disney,animation,cinderella,kids,animated,family,children,king,little,lion
Topic 11,kelly,musical,dance,sinatra,music,dancing,songs,gene,singing,astaire
Topic 12,seen,ve,best,movies,10,times,films,haven,say,amazing
Topic 13,horror,house,creepy,scary,gore,budget,halloween,films,fans,effects
Topic 14,great,acting,really,actors,cast,job,story,wonderful,loved,music
Topic 15,action,jackie,chan,scenes,fu,kung,fight,martial,bourne,arts
Topic 16,love,beautiful,romantic,wonderful,heart,loved,romance,fall,absolutely,watch
Topic 17,life,story,people,real,world,war,family,characters,lives,way
Topic 18,book,jane,version,read,eyre,novel,rochester,dalton,tarzan,emma
Topic 19,game,games,bond,play,graphics,fun,10,mario,64,missions
Topic 20,like,really,think,don,just,know,people,say,didn,lot

In [33]:
# Create a topic mapping

topic_mapping = {
    'Topic 4': 'TV',
    'Topic 7': 'Sci-fi',
    'Topic 8': 'Comedy',
    'Topic 10': 'Animation',
    'Topic 11': 'Musical',
    'Topic 12': 'Book Adaptation',
    'Topic 13': 'Horror',
    'Topic 15': 'Martial Arts / Action',
    'Topic 16': 'Romance',
    'Topic 17': 'War',
    'Topic 18': 'Book Adaptations',
    'Topic 19': 'Game Adaptations'
}

In [35]:
# Recall the document-topic matrix, W

W = pd.DataFrame(W, columns=[f'Topic {i + 1}' for i in range(N_TOPICS)])
W['max_topic'] = W.apply(lambda x: topic_mapping.get(x.idxmax()), axis=1)
Film_topics = W[pd.notnull(W['max_topic'])]

In [36]:
Film_topics.columns

Index(['Topic 1', 'Topic 2', 'Topic 3', 'Topic 4', 'Topic 5', 'Topic 6',
       'Topic 7', 'Topic 8', 'Topic 9', 'Topic 10', 'Topic 11', 'Topic 12',
       'Topic 13', 'Topic 14', 'Topic 15', 'Topic 16', 'Topic 17', 'Topic 18',
       'Topic 19', 'Topic 20', 'max_topic'],
      dtype='object')

In [ ]:
# Film types by review topics
Film_topics['max_topic'].value_counts()

max_topic
War                      557
Horror                   536
Romance                  470
Book Adaptation          415
TV                       396
Book Adaptations         366
Martial Arts / Action    357
Comedy                   343
Sci-fi                   336
Musical                  310
Animation                290
Game Adaptations         212
Name: count, dtype: int64

In [41]:
topics = Film_topics['max_topic'].unique()

In [56]:
review_samples = {}

# Random sampling 2 review-indices based on topics
for topic in topics:
    review_samples[topic] = Film_topics[Film_topics['max_topic'] == topic].sample(2).index.values

# Printing reviews of topic based sampled indices
for key, vals in review_samples.items():
    print(f'Topic: {key}')
    for idx in vals:
        print(reviews[idx])
        print()
    print('-'*100)

Topic: TV
Well its about time. I had really given up any and all hope that there was going to be a standout episode among this season's entries. While there have still been far too many drab to hohum entries, at least this episode turned out well. Its rather funny that director Rob Schmidt who only has the not bad Wrong Turn to his credit and writer John Esposito whose only scripting chores to date have included Tale Of The Mummy and Graveyard Shift should be the ones to give us the best written and most thought provoking episode of the season. In "Right To Die" we are treated to the story of Cliff and Abbey. At the start of the episode the couple are having a conversation. Abbey has caught Cliff cheating and he is desperately trying to win her back. While they speak, they find themselves in a car accident where Cliff is left with only scratches and bruises, but Abbey is thrown from the car and catches on fire when a spark ignites and gasoline that had dripped onto her catches her on fire. And this is just the setup people. Once in the hospital Cliff must decide whether or not Abbey should live in this state with no skin and only nerve reflexes. There's also a side effect too. Every time she flatlines, Abbey goes a walking as a ghost and causes trouble for all sorts of people. Hands down this is the best episode of the season and certainly ranks as one of the top episodes ever. From the gruesome effects to the taut script which threw in a few twists I never saw coming and suspense so palpable you can almost touch it, Right To Die should have the right to go on living forever.

Granted I had seen some "Speed Racer", but I never really watched it and I had also seen other shows some featuring these characters dressed as birds who flew a ship called the Phoenix and another revolving around a space ship that looked like a giant ocean vessel and it flew backwards at times for some reason and was really dark and hard to understand for someone who was maybe five. This one though I watched nearly every episode and the amazing to me at the time was that this show had some resolution to it. It actually ended, the bad guys done in unlike nearly every American cartoon where nothing really concludes such as the last episode of the generation one Transformers that ended with Galvatron and this new bad guy vowing to get the Autobots, Dungeons and Dragons with the kids never making it home, with GI Joe with Cobra still out there ready to try again and so on and so forth. This one did end and did feature a rather cool robot that got new weapons as the show progressed, it was a bit bland to begin with as it could not fly and had only a few really cool weapons. As it went on he got a cool shooting fist like the one Android 16 used against Cell in Dragonball Z, then that weapon evolved to include razors that shot out. Then the big robot even got wings so he could fly and even more weapons were incorporated into the wings. He would also get a couple of allies in a female robot and a rather funny one called Bobo in America. The villains not only consisted of Dr. Hell, but a really weird person that was half man half woman and a dude with a flying head. Interesting show and it was kind of nice seeing a conclusion.

----------------------------------------------------------------------------------------------------
Topic: Martial Arts / Action
Although John Woo's hard Boiled is my number 1 favorite movie. But i have to say police story is my number 2 favorite movie. I say this because the stunts, the fights and the action my favorite part of the movie is when Jackie Chan jumps off the rail at the top of the esculator at the mall grabs on to a pole surrounded with Chrismas lights and slid down the pole fell through a skylight and finally land on his back on the hard marble floor. OUCH! Buy it at amazon.com for 14:98. (Or something in 14 dollars.)VHS new line home video. any questions or comments please feel free to reply. (i'm only 14 but i know where you can find any movie ever made.) if you looking everywhere for a movie and can't find it please reply to me. Thank you and good night!

It's remarkable and quite praiseworthy how writers and directors continue to make great movies out of one of the oldest and most (over)used story lines in cinema! "Dog Bite Dog" is basically not much more than just the simple story of an lone copper obsessively chasing a brilliant criminal, only Pou-Soi Cheang distinguishes his film from the rest by being extremely violent & relentless. This is unquestionably one of the grittiest and most uncompromising movies I've ever seen, with an atmosphere of constant nihilism and characters that seem to come walking straight out of hell! Not even the installments in Chan-Wook Park's trilogy of vengeance (with the exception of "Oldboy", perhaps) or any other infamous Cat-III film ever released were as sadistic and brutal as some of the events depicted in "Dog Bite Dog". Pang is a young and ruthless Cambodian assassin who lands in the crowded streets of Hong Kong to eliminate the wife of an eminent judge in a restaurant. When the police arrives at the place, young officer Wai sees how Pang hastily flees from the scene of the crime and follow him. The first actual confrontation between the two rabid dogs results in a gigantic blood bath, as Pang mercilessly kills several hostages and even Wai's long time friend and colleague. From then on begins a thrilling and action-packed cat and mouse game between the frustrated cop and the professional killer. The latter also saves a young girl from the constant sexual abuse of her father and stays with her at her shed in the local garbage dump. What makes this routine action/thriller so fascinating (apart from the explicit violence) are the main characters' backgrounds! Pang, the hit-man, is a Cambodian orphan and has been trained to fight & kill for money ever since he was a child. He knows no restrictions, has no mercy and barely speaks a word. Wai, the cop, became particularly ruthless and unorthodox ever since his role-model father (also a cop) lies in a coma after a drug-related incident. Lai doesn't question suspects and witnesses; he yells at them and he's prepared to sacrifice everything in order to stop his brand new nemesis. People with a weak stomach or tangled nerves are advised to stay away from this film, because the cruelty and shocks featuring in "Dog Bite Dog" can easily cause nausea. It's not the type of violence where bloodied heads and chopped off limbs fly through the air, but more like the intense and utterly disturbing type where people attempt to crush their opponents mentally as well as physically. The filming locations are effectively dark and eerie and the extremely sober music makes the already harrowing tone of the movie even more petrifying. The performances are terrific! I wouldn't be surprised if Edison Chen and Sam Lee treated each other like enemies on the film set as well, because their on screen hatred and disgust feels a little too legitimate. "Dog Bite Dog" is a powerful and unforgettable film, highly recommended if you can stomach it. If you fear you can't, just wait a few years for the inevitable American remake which will unquestionably soften the premise a little.

----------------------------------------------------------------------------------------------------
Topic: Book Adaptations
When I was a kid it was Lex Barker's time as Tarzan. I often heard from older people that Johnny Weissmuller "was" Tarzan and I wouldn't understand why since I saw a couple of Weismuller's last films in the character and I thought he was sort of out of shape. It wasn't after many years that I came across "Tarzan and His Mate", and then I understood. Weismuller is in shape in this picture and has the presence and rugged looks the character demands not matched yet by other Tarzans such as Barker, Gordon Scott, Jock Mahoney, Denny Miller, Miles O'Keefe and Cristopher Lambert.<br /><br />As for this film I was also surprised by the sensual presence of beautiful Maureen O'Sullivan a strong, self minded, active and "no-inhibitions" woman as Jane way ahead of the times in which the film was made (Tarzan pushes her into a pond naked as she is amused; one of the explorers kisses her by surprise and though she doesn't kiss him back she sort of let him do for a bit and makes no big deal out of it); such behaviors were unthinkable with the "Janes" to come such as Brenda Joyce, Vanessa Brown, Virginia Huston or Dorothy Hart, all playing sort of too perfect sweet vulnerable women making it hard to believe they could survive in a hostile place like the African jungle.<br /><br />O'Sullivan character's sparkling personality steals the show out of Tarzan himself, except of course when it comes to action and Weismuller takes the lead easily; the combination is perfect. Another highlight in the movie is Cheeta's secondary role and not as the main lead like in later Tarzan pictures where she often saves the day.<br /><br />"Tarzan and His Mate" stands as a fine product in its genre (Tarzan films) and perhaps as the best, though I have to admit that I also enjoyed "Tarzan's Greatest Adventure" (1959) made with a higher budget and a strong supporting cast (and in spite of the just acceptable Gordon Scott in the leading role with his too perfect "all gymnasium" physical looks that doesn't fit for a rustic ape man).<br /><br />Good for Jane and her mate!

I saw a lot films about Charles Dickens' Christmas Carol. But this one is the best of all! There is an atmosphere which is exactly the same as in the book. The actors (George C. Scott and others) are great! Unfortunately, you can't often watch the film in Germany and Switzerland.

----------------------------------------------------------------------------------------------------
Topic: Horror
Why does this have such a low rating? I really don't get it... Is it because of the bad acting? The bad dialogue? Well, who cares about these things in cheesy low-budget horror movies? Seriously, the acting and the dialogue isn't important in those movies. People who hate movies only because of bad acting and bad dialogue shouldn't be allowed to rate cheesy low-budget movies. Those movies shouldn't be taken seriously. Period.<br /><br />Anyway, time to talk about the movie, right? Well, I loved it! I bought it because I expected a gorefest, but it's not a gorefest and the gore is pretty bad (most of the time it's just animal guts placed on the body of the actors and that's lame), but I didn't really care because the movie is hilarious! The characters are hilarious, the acting is hilarious (bad acting is a GOOD thing in cheesy low-budget horror movies), the dialogue is hilarious (bad dialogue is a GOOD thing in cheesy low-budget horror movies), the zombie rapist with a huge dick is hilarious, the flying demon baby is hilarious and I could go on and on and on, but I don't want to say too much... BUT I have to mention that there's a scene in which a girl masturbates a sex doll like it's alive lol! Oh and the zombie rapist falls in love with the sex doll lol!<br /><br />Best lines in the movie:<br /><br />Detective Manners: *sniffs coke* Detective Sloane: What the *beep* are you doing, Manners? What the hell did you snort? What the hell is that? Detective Manners: It's nothing man, it's... Ehh... Cold medicine...<br /><br />Detective Manners: *injects heroin in his arm* Detective Sloane: What the *beep* are you doing, Manners? Are you *beep* insane? Detective Manners: It's cold medicine.<br /><br />Detective Manners: *repeatedly kicks a random guy in the face* Detective Sloane: What the hell's going on, Manners? What are you doing? Detective Manners: This maniac was rambling about demons and then he started smashing his head on the rock! He just started smashing his head on the rock! I think he's on PCP or something!<br /><br />LOL!

I remember being terrified of movie blood when I was younger, and gradually getting less so, until getting jaded enough, as I'm sure many other viewers have become, so that the barrage of gory films produced in last few years have entertained me but not scared me or made me squirm. "The Dentist" turned that around.<br /><br />The setup seems simple: a mentally unstable dentist wreaks havoc on the insides of mouths, and perhaps bodies as well. A clever twist, though, is that the dentist is the film's protagonist, so instead of being some one-dimensional bad guy with no clear motivation, his development is the most extensive of any character and he is very human and believable. The viewer thus feels sympathy for him as well as his victims, and instead of hoping for justice to come to him, I found myself hoping he would somehow find a way to cover up his tracks and return to a normal life.<br /><br />What really "makes" a horror movie is the violence. And "The Dentist" does it better than any other film I can think of. First off, the film has tons of tension, which is something that modern gore films tend to lack. In one scene (), the dentist is emotionally distraught and has to see a young child patient for the first time. As he reaches into the child's mouth, you hope that, for the dentist's and the child's sake, the encounter ends without injury. I won't spoil what happens. Second, when the gore does come, it hits all the worst, squirmy nerves. Once again, I won't give anything away.<br /><br />Of course, being a movie that you've never heard of, it does have flaws. Most importantly, it's exclusively for horror fans. Also, as another reviewer mentioned, by taking place over a span of just a few days, we don't really get any background on the characters. And the tension drops a little bit during the very end. But really, the fact that we would even want to know background about the characters is evidence to how good it is, and the bulk of the film is solid enough that any small lapses in tension can be forgiven.<br /><br />It's strange, after years of being accustomed to movie gore, to suddenly want to cover my eyes at the sight of blood. "The Dentist" made me scared and thoroughly uncomfortable, and for this it earns my full approval.

----------------------------------------------------------------------------------------------------
Topic: Romance
hi, im scott (A.K.A woody7739) i Love the film Twisted Desire, And i love watching Melissa Joan Hart on the t.v as i think she is fine. I am a real fan of sabrina the teenage witch too, so this helped my watch it (don't ask). i love the way that nicole plans out her parents murder very carfully, as she makes sure that someone else pulls the trigger and practices on the bottles, so she wont give away her fingerprints (a very well planned out idea), back i guess it all backfired on nicole as she got caught as her old boyfriend comes along and puts a hidden camera under his shirt. i give this film a nine out of ten, and put it in MY top 10 films list. And last but not least if anyone see's this film in the shops please tell me as i seen it on tv and didn't record it. bye

Have not seen this 1958 film in a very long time and greatly enjoyed Kim Novak playing the role as Gil Holroyd who is an actual witch and has an aunt named Queenie Holroyd who is also a witch and Gillian also has a brother warlock named Nick played by Jack Lemmon. When Gillian sets her eyes on Shep Henderson,(James Stewart) who is engaged to a girl he is going to marry; Gillian performers some magic spells with a cat and changes his mind about his intended bride and then becomes very lust full and falls in love with Gillian. The story tells that a real witch cannot fall in love, blush or cry and this begins to prove a big problem between Shep and Gillian, so Nick and Aunt Queenie decided they have to do something about this situation. Great film to view over and over again and a great classic film from 1958.

----------------------------------------------------------------------------------------------------
Topic: War
There be very little doubt that HG Wells is the most influential writer of the 20th century . Jules Verne has some claim to be the father of science fiction but his stories were more adventure stories using marvellous inventions as plot devices . Wells was profound and brought subtext to his tales . Perhaps his greatest legacy is that there's very little if any evidence that people believed in life on other planets before the 20th century where as now many people including Richard Dawkins consider it a near certainty . There's no evidence of this of course and one can't help wondering that is was Wells who introduced this to human thinking ? Undoubtedly it was Wells that planted the seed .<br /><br />THINGS TO COME was adapted by Wells himself from his own novel . It is rather obvious however that he is unable to tell the difference between the technicalities of writing novels and writing screenplays . The dialouge is often laden , heavy handed and unconvincing . One case in point is the two pilots from opposing sides discussing the nature of war " Why must we murder one another . Why ? " This mirrors the criticism , near naked contempt that Orwell had of Wells in his essay Wells , Hitler And The World State and it is true that Wells anti-war message is painfully overstated . It'd be impossible to believe a conversation taking place between an RAF pilot and his opposite number in the Luftwaffe a few years later <br /><br />That said it is absolutely fascinating watching a film from 1935 predicting a world wide war taking place in 1940 that heralds the end of civilisation . There's a striking and haunting imagery as a child bangs a drum as a phantom army marches in the background and the collapse of society and the fear of The Wanderng Sickness is wonderfully realised . Even the rather lazy storytelling of showing the year of the setting has a compelling nature It's the images that makes this film along with Arthur Bliss score that makes the film so memorable . And to be fair Wells does ask the question " The universe or nothing . What shall it be ? " . In short this is a film whose flaws are easy to forgive

I enjoyed watching Brigham Young and found it to be a positive and largely true portrayal of the LDS faith. I think that a remake of this epic journey across the plains would be beneficial, since many people today are not familiar with the trials and persecutions faced by the early Mormon church. It is an incredible story of a strong and devoted people.<br /><br />As a member of the church, the single most disturbing aspect of the film (most of the historical inaccuracies did not bother me much) was the portrayal of Brigham Young as one that had "knowingly deceived" church members into believing he had been called to be Joseph's successor as the prophet. Although I understand the dramatic reasons for this plot line, it creates the impression that his doubts in this regard are historical fact, when in reality, both Brigham and the bulk of the church members understood and believed firmly that he had been called to lead the church. Brigham did not knowingly deceive the saints; rather he led them confidently by inspiration. The point is important for Mormons because on it hinges an important aspect of our faith: that God truly speaks to prophets today, and that Brigham Young, like Joseph Smith, was an inspired prophet of God.<br /><br />Whether or not you believe this statement or not, just know that the film does not accurately portray what Brigham himself believed.

----------------------------------------------------------------------------------------------------
Topic: Book Adaptation